language: node_js
sudo: required
dist: trusty
node_js:
  - "8"
  - "9"
before_install: if [[ `npm --version` != "5.8.0" ]]; then npm install -g npm@latest; npm --version; fi
matrix:
  fast_finish: true
services:
  - mongodb
  - docker
script: make travis
after_success:
  - nvm version
  - if [[ ! -z "$DOCKER_USER" ]]; then docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && git checkout -- . && git clean -fd . && make docker_release; fi
after_script: make report
