language: node_js
sudo: false
node_js:
  - 0.10
  - 0.12
  - 4
  - 5
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 4
    - node_js: 5
services: mongodb
script: make travis
after_script: make report
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
